// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-3Nu_k0E4llHqph4UV6CzYb3q90CvfWk',
    appId: '1:127546533956:web:871a67e3189e4c35b87411',
    messagingSenderId: '127546533956',
    projectId: 'proboscis-2025',
    authDomain: 'proboscis-2025.firebaseapp.com',
    storageBucket: 'proboscis-2025.firebasestorage.app',
    measurementId: 'G-HD8FJY9GRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlBZYtxFLoYMa3X3gtLBARqV3SYpkf4b8',
    appId: '1:127546533956:android:3dc248217f1439e7b87411',
    messagingSenderId: '127546533956',
    projectId: 'proboscis-2025',
    storageBucket: 'proboscis-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBx8NpMO7EBFQt1UDMgTmqhvhxAn2XQ5I',
    appId: '1:127546533956:ios:b535abb5dc358b5db87411',
    messagingSenderId: '127546533956',
    projectId: 'proboscis-2025',
    storageBucket: 'proboscis-2025.firebasestorage.app',
    iosBundleId: 'com.example.jidoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBx8NpMO7EBFQt1UDMgTmqhvhxAn2XQ5I',
    appId: '1:127546533956:ios:b535abb5dc358b5db87411',
    messagingSenderId: '127546533956',
    projectId: 'proboscis-2025',
    storageBucket: 'proboscis-2025.firebasestorage.app',
    iosBundleId: 'com.example.jidoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-3Nu_k0E4llHqph4UV6CzYb3q90CvfWk',
    appId: '1:127546533956:web:fbf2900ada647aaab87411',
    messagingSenderId: '127546533956',
    projectId: 'proboscis-2025',
    authDomain: 'proboscis-2025.firebaseapp.com',
    storageBucket: 'proboscis-2025.firebasestorage.app',
    measurementId: 'G-EDDMZSRRTP',
  );
}
